<%
  const daemonExtraArgsFmt = locals.daemonExtraArgs && ', ' + daemonExtraArgs.map(_ => `"${_}"`).join(', ');
  const portsFmt = [rpcPort, locals.p2pPort, locals.testnetRpcPort, locals.testnetP2pPort, locals.zmqpubrawblockPort, locals.zmqpubrawtxPort].filter(Boolean).join(' ');
  const binaryPrefix = locals.binaryPrefix || nodePrefix;
  const nodeUrl = locals.nodeUrl ? locals.nodeUrl : `${nodeBaseUrl}$NODE_FILENAME`;
  const useZip = nodeUrl.endsWith('.zip');
  const extraAptPackages = locals.extraAptPackages || [];
  const aptPackages = ['ca-certificates', 'wget', ...extraAptPackages];
-%>
FROM ubuntu:18.04

# System
RUN apt-get update -qq \
  && apt-get install -qq --no-install-recommends <%- aptPackages.join(' ') %> \
  && rm -rf /var/lib/apt/lists/*

ARG NODE_VERSION
ENV NODE_PREFIX=<%- nodePrefix %>
ENV NODE_FILENAME <%- locals.nodeFilename || '$NODE_PREFIX-$NODE_VERSION-x86_64-linux-gnu.tar.gz' %>
ENV NODE_URL <%- nodeUrl %>

# Node
RUN set -ex \
  && wget -qO $NODE_FILENAME $NODE_URL \
  && tar -xzf *.tar.gz --exclude=*-qt --exclude=*test* \
  && mv $NODE_PREFIX-*/bin/* /bin \
  && rm -rf $NODE_PREFIX-* \
  && which <%- binaryPrefix %>d

<% if (name === 'zcash') { -%>
RUN ln -s /data/zcash-params /root/.zcash-params
<% } -%>

VOLUME /data
EXPOSE <%- portsFmt -%>

ENTRYPOINT ["/bin/<%- binaryPrefix %>d", "-datadir=/data", "--printtoconsole"<%- daemonExtraArgsFmt %>]
