<%
  const portsFmt = [rpcPort, locals.p2pPort].filter(Boolean).join(' ');
-%>
FROM golang:1.12-alpine as builder

# System
RUN apk add --no-cache --update alpine-sdk git make

# Node
RUN echo "Cache bust to version <%= nodeVersion %>"

RUN go get -d github.com/lightningnetwork/lnd \
  && cd /go/src/github.com/lightningnetwork/lnd \
  && make \
  && make install

# Final image
FROM alpine as final

# Force Go to use the cgo based DNS resolver. This is required to ensure DNS
# queries required to connect to linked containers succeed.
ENV GODEBUG netdns=cgo

# Expose lnd ports (server, rpc).
EXPOSE <%- portsFmt -%>

# Copy the binaries and entrypoint from the builder image.
COPY --from=builder /go/bin/lncli /bin/
COPY --from=builder /go/bin/lnd /bin/

VOLUME /data

ENTRYPOINT ["/bin/lnd", "--datadir=/data"]
